---
# - name: Configure VPN to a VPS
- hosts: all
  become: true

  # vars_files:
  #   - custom.yml
  #   - secret.yml

  handlers:
    - name: Import global handlers
      ansible.builtin.import_tasks: handlers/main.yml

  # pre_tasks:
  #   - name: Set the AWS and Letsencrypt staging facts
  #     ansible.builtin.set_fact:
  #       aws: "{{ lookup('ansible.builtin.env', 'AWS_EC2') == 'true' }}"
  #       letsencrypt_staging: "{{ [lookup('ansible.builtin.env', 'LETSENCRYPT_STAGING') | lower | default('no')] }}"

  roles:
    ###
    ### Requirements
    ###

    - role: system
      tags:
        - system

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    - role: docker_network
      tags:
        - docker

    ###
    ### Required Roles
    ###

    - role: fail2ban
      when: enable_fail2ban | default(False)
      tags:
        - fail2ban

    - role: dns
      when: enable_adguard_unbound_doh | default(False)
      tags:
        - dns

    - role: authelia
      tags:
        - authelia

    - role: bunkerweb
      tags:
        - bunkerweb

    - role: wireguard
      tags:
        - wireguard

    - role: chriswayg.msmtp-mailer
      when: email_password is defined
      tags:
        - msmtp

    - role: ssh
      tags:
        - ssh

    ###
    ### Applications
    ###
    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns
      when: (cloudflare_ddns_enabled | default(False))
