---
##    
##    ██╗   ██╗██╗  ████████╗██╗███╗   ███╗ █████╗ ████████╗███████╗
##    ██║   ██║██║  ╚══██╔══╝██║████╗ ████║██╔══██╗╚══██╔══╝██╔════╝
##    ██║   ██║██║     ██║   ██║██╔████╔██║███████║   ██║   █████╗  
##    ██║   ██║██║     ██║   ██║██║╚██╔╝██║██╔══██║   ██║   ██╔══╝  
##    ╚██████╔╝███████╗██║   ██║██║ ╚═╝ ██║██║  ██║   ██║   ███████╗
##     ╚═════╝ ╚══════╝╚═╝   ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝
##                                                                  
##    ██████╗ ███████╗██╗   ██╗ ██████╗ ██████╗ ███████╗            
##    ██╔══██╗██╔════╝██║   ██║██╔═══██╗██╔══██╗██╔════╝            
##    ██║  ██║█████╗  ██║   ██║██║   ██║██████╔╝███████╗            
##    ██║  ██║██╔══╝  ╚██╗ ██╔╝██║   ██║██╔═══╝ ╚════██║            
##    ██████╔╝███████╗ ╚████╔╝ ╚██████╔╝██║     ███████║            
##    ╚═════╝ ╚══════╝  ╚═══╝   ╚═════╝ ╚═╝     ╚══════╝            
##                                                                  
##    ███╗   ██╗ █████╗ ███████╗                                    
##    ████╗  ██║██╔══██╗██╔════╝                                    
##    ██╔██╗ ██║███████║███████╗                                    
##    ██║╚██╗██║██╔══██║╚════██║                                    
##    ██║ ╚████║██║  ██║███████║                                    
##    ╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝   
##       ultimate-devops-nas      https://github.com/ctalaveraw/ultimate-devops-nas
# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Example options
ansible_nas_hostname: devops-nas
ansible_nas_timezone: Etc/UTC

## Enable some applications
dashy_enabled: true
portainer_enabled: true
