---
- name: Start Baïkal
  block:
    - name: Create Baïkal Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ baikal_data_directory }}"

    - name: Baïkal
      docker_container:
        name: "{{ baikal_container_name }}"
        image: ckulka/baikal:nginx
        pull: true
        volumes:
          - "{{ baikal_data_directory }}/config:/var/www/baikal/config:rw"
          - "{{ baikal_data_directory }}/data:/var/www/baikal/Specific:rw"
        ports:
          - "{{ baikal_port }}:80"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ baikal_user_id }}"
          PGID: "{{ baikal_group_id }}"
        restart_policy: unless-stopped
        memory : "{{ baikal_memory }}"
        labels:
          traefik.enable: "{{ baikal_available_externally | string }}"
          traefik.http.routers.baikal.rule: "Host(`{{ baikal_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.baikal.tls.certresolver: "letsencrypt"
          traefik.http.routers.baikal.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.baikal.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.baikal.loadbalancer.server.port: "80"
  when: baikal_enabled is true

- name: Stop Baïkal
  block:
    - name: Stop Baïkal
      docker_container:
        name: "{{ baikal_container_name }}"
        state: absent
  when: baikal_enabled is false
