---
# enable or disable the application
firefly_enabled: false
firefly_available_externally: false

# directories
firefly_data_directory: "{{ docker_home }}/firefly"

# network
firefly_hostname: "firefly"
firefly_port: "8066"

# specs
firefly_#memory: "1g"
firefly_mysql_#memory: "1g"

# docker
firefly_container_name: firefly
firefly_mysql_container_name: firefly-mysql
