---
- name: Start Dashy
  block:
    - name: Create Dashy Directories
      file:
        path: "{{ item }}"
        state: directory
        # mode: 0755
      with_items:
        - "{{ dashy_config_directory }}"
    - name: Dashy Docker Container
      docker_container:
        name: "{{ dashy_container_name }}"
        image: lissy93/dashy:latest
        pull: true
        ports:
          - "{{ dashy_port }}:80"
        volumes:
          # - "{{ dashy_config_directory }}/:/app/public/:rw"
        restart_policy: unless-stopped
        memory: "{{ dashy_memory }}"
        labels:
          traefik.enable: "{{ dashy_available_externally | string }}"
          traefik.http.routers.dashy.rule: "Host(`{{ dashy_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dashy.tls.certresolver: "letsencrypt"
          traefik.http.routers.dashy.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.dashy.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.dashy.loadbalancer.server.port: "80"
  when: dashy_enabled is true

- name: Stop Dashy
  block:
    - name: Stop Dashy
      docker_container:
        name: "{{ dashy_container_name }}"
        state: absent
  when: dashy_enabled is false
