---
mosquitto_enabled: false

# directories
mosquitto_data_directory: "{{ docker_home }}/mosquitto"

# uid / gid
mosquitto_user_id: "1001"
mosquitto_group_id: "1001"

# network
mosquitto_port_a: "1883"
mosquitto_port_b: "9001"

# specs
mosquitto_memory: 1g
