[entryPoints]
  [entryPoints.web]
    address = ":{{ traefik_port_http }}"

  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"

  [entryPoints.websecure]
    address = ":{{ traefik_port_https }}"

      [entryPoints.websecure.http.tls]
        certResolver = "letsencrypt"

        [entryPoints.websecure.http.tls.domains]
          main = "{{ vps_vpn_domain }}"
          sans = [
            "*.{{ vps_vpn_domain }}"
          ]

  [entryPoints.traefik]
    address = ":{{ traefik_port_ui }}"

[serversTransport]
  insecureSkipVerify = true

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    exposedbydefault = false

[api]
  insecure = true
  dashboard = true

[log]
  level = "{{ traefik_log_level }}"

[ping]
  terminatingStatusCode = 0

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "{{ vps_vpn_email }}"
      storage = "/letsencrypt/acme.json"
      caserver = "{{ traefik_acme_server }}"

      [certificatesResolvers.letsencrypt.acme.dnsChallenge]
        provider = "{{ traefik_dns_provider }}"
      