image: hashicorp/packer:1.8

stages:
  - test
  - build

test-packer-deployment-validate:
  stage: test
  script:
    - echo "Checking if Packer deployment is valid..."
    - packer validate ./nas_host.pkr.hcl 

build-proxmox-vm-template:
  stage: build
  script:
    - echo "Building Proxmox VM template with Packer..."
    - packer build -var-file="./secrets.pkr.hcl" nas_host.pkr.hcl 
  dependencies:
    - test-packer-deployment-validate
  artifacts:
    paths:
      - ../artifacts/template-ultimate-nas.qcow2