---
plex_enabled: false
plex_available_externally: false
plex_available_local_dns: false

# directories
plex_config_directory: "{{ docker_home }}/plex/config"
plex_logs: "{{ docker_home }}/plex/logs"
plex_movies_directory: "{{ movies_root }}"
plex_tv_directory: "{{ tv_root }}"
plex_photos_directory: "{{ photos_root }}"
plex_podcasts_directory: "{{ podcasts_root }}"
plex_music_directory: "{{ music_root }}"
plex_audiobooks_directory: "{{ audiobooks_root }}"

# uid / gid
plex_user_id: "0"
plex_group_id: "0"

# If you're paranoid, set permissions to "ro" so Plex won't ever be able to
# delete your files
plex_movies_permissions: "rw"
plex_tv_permissions: "rw"
plex_photos_permissions: "rw"
plex_podcasts_permissions: "rw"
plex_music_permissions: "rw"
plex_audiobooks_permissions: "rw"

# network
plex_hostname: "plex"
plex_port_container_ui: "32400"
plex_port_ui: "{{ plex_port_container_ui }}"


# Traefik rules for local DNS
plex_traefik_rules_internal: 
  - traefik.http.routers.plex-local.rule: 'Host(`{{ plex_hostname }}.{{ ansible_nas_domain_local }}`)'
  - traefik.http.routers.plex-local.tls.certresolver: 'letsencrypt'
  - traefik.http.routers.plex-local.tls.domains[0].main: '{{ ansible_nas_domain_local }}'
  - traefik.http.routers.plex-local.tls.domains[0].sans: '*.{{ ansible_nas_domain_local }}'
  - traefik.http.services.plex-local.loadbalancer.server.port: '32400'
  - traefik.http.routers.plex-local.service: '{{ plex_hostname }}-local'
  - traefik.http.routers.plex-local.priority: '2'

# specs
plex_memory: "2g"

# Device mappings for the docker container. E.g. To enable hardware transcoding:
# plex_devices:
#  - "/dev/dri:/dev/dri"

# see https://hub.docker.com/r/linuxserver/plex for details on this setting
plex_version: "docker"
