---
- hosts: all

  roles:
    ###
    ### Requirements
    ###
    - role: ansible-nas-users
      tags:
        - ansible-nas-users
        - ansible-nas

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    ###
    ### Ansible-NAS Roles
    ###
    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas

    - role: ansible-nas-docker
      tags:
        - ansible-nas-docker
        - ansible-nas

    ###
    ### Applications
    ###
    - role: gitlab
      tags:
        - gitlab
      when: (gitlab_enabled | default(False))

    - role: gitea
      tags:
        - gitea
      when: (gitea_enabled | default(False))

    - role: jenkins-controller
      tags:
        - jenkins-controller
        - jenkins
      when: (jenkins_controller_enabled | default(False))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))
