---
linkding_enabled: false
linkding_available_externally: false

# directories
linkding_data_directory: "{{ docker_home }}/linkding/config"

# uid/gid
linkding_user_id: "0"
linkding_group_id: "0"

# network
linkding_port: "9999"
linkding_hostname: "linkding"
linkding_container_name: "{{ linkding_hostname }}"
linkding_domain_external: "{{ linkding_hostname }}.{{ ansible_nas_domain }}"
linkding_domain_allowed: "https://{{ linkding_domain_external }}"

# specs
linkding_memory: 1g
