---
snapraid_cron_sync_enabled: false

# Defines "minute (0-59)"
snapraid_cron_sync_minute: "0"

# Defines "hour (0-23)"
snapraid_cron_sync_hour: "*/2"

# Defines "day of the month (1-31)"
snapraid_cron_sync_day_of_month: "*"

# Defines "month (1-12)"
snapraid_cron_sync_month: "*"

# Defines "day of the week (0-6)"
snapraid_cron_sync_day_of_week: "*"

