---
- name: Install dirmngr
  become: true
  apt:
    name: dirmngr
    state: present
    update_cache: true

- name: Install SnapRAID
  become: true
  apt:
    name: snapraid
    state: present
    update_cache: true
