---
##    
##    ██╗   ██╗██╗  ████████╗██╗███╗   ███╗ █████╗ ████████╗███████╗
##    ██║   ██║██║  ╚══██╔══╝██║████╗ ████║██╔══██╗╚══██╔══╝██╔════╝
##    ██║   ██║██║     ██║   ██║██╔████╔██║███████║   ██║   █████╗  
##    ██║   ██║██║     ██║   ██║██║╚██╔╝██║██╔══██║   ██║   ██╔══╝  
##    ╚██████╔╝███████╗██║   ██║██║ ╚═╝ ██║██║  ██║   ██║   ███████╗
##     ╚═════╝ ╚══════╝╚═╝   ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝
##                                                                  
##    ██████╗ ███████╗██╗   ██╗ ██████╗ ██████╗ ███████╗            
##    ██╔══██╗██╔════╝██║   ██║██╔═══██╗██╔══██╗██╔════╝            
##    ██║  ██║█████╗  ██║   ██║██║   ██║██████╔╝███████╗            
##    ██║  ██║██╔══╝  ╚██╗ ██╔╝██║   ██║██╔═══╝ ╚════██║            
##    ██████╔╝███████╗ ╚████╔╝ ╚██████╔╝██║     ███████║            
##    ╚═════╝ ╚══════╝  ╚═══╝   ╚═════╝ ╚═╝     ╚══════╝            
##                                                                  
##    ███╗   ██╗ █████╗ ███████╗                                    
##    ████╗  ██║██╔══██╗██╔════╝                                    
##    ██╔██╗ ██║███████║███████╗                                    
##    ██║╚██╗██║██╔══██║╚════██║                                    
##    ██║ ╚████║██║  ██║███████║                                    
##    ╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝   
##       ultimate-devops-nas      https://github.com/ctalaveraw/ultimate-devops-nas

# Define the path for mergerfs storage mount
ansible_nas_mergerfs_mount_path: /mnt/mergerfs_storage

## mergerfs storage configuration
mergerfs_enabled: true

# Mergerfs mountpoints to create. For example:
# mergerfs_mounts: []
mergerfs_mounts:
  - path: "{{ ansible_nas_mergerfs_mount_path }}"
    branches:
      - /mnt/disk0
      - /mnt/disk1
      - /mnt/disk2
      - /mnt/disk3
    options: defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,dropcacheonclose=true,fsname=mergerfs

## snapraid storage configuration
snapraid_enabled: true

# Defines the data disks to use.
# The name and mount point association is relevant for parity, do not change it
# WARNING: Adding here your /home, /var or /tmp disks is NOT a good idea!
# SnapRAID is better suited for files that rarely changes!
# e.g.
# snapraid_data_disks:
#   - name: data1
#     path: /mnt/data1
#   - name: data2
#     path: /mnt/data2
#     smartctl_options: -d usbjmicron %s

# snapraid_parity_disks: []
snapraid_data_disks: 
  - name: disk0
    path: /mnt/disk0
  - name: disk1
    path: /mnt/disk1
  - name: disk2
    path: /mnt/disk2
  - name: disk3
    path: /mnt/disk3
    smartctl_options: -d usbjmicron %s

# Defines the disks to use as parity storage.
# It must NOT be a data disk
# If more than one parity disk is specified, they enable the multiple failures
# protection from two to six level of parity.
# e.g.
# snapraid_parity_disks:
#   - path: /mnt/parity1
#   - path: /mnt/parity2
#     smartctl_options: -d areca,1/1 /dev/sg0

# snapraid_parity_disks: []
snapraid_parity_disks:
  - path: /mnt/parity0
    smartctl_options: -d areca,1/1 /dev/sg0

# Defines the files to use as content list
# You must have least one copy for each parity file plus one. Some more don't hurt
# They can be in the disks used for data, parity or boot, but each file must be
# in a different disk
# e.g.
# snapraid_content_files:
#   - /mnt/data1/snapraid.content
#   - /mnt/data2/snapraid.content

# snapraid_content_files: []
snapraid_content_files:
  - /mnt/disk0/snapraid.content
  - /mnt/disk1/snapraid.content
  - /mnt/disk2/snapraid.content
  - /mnt/disk3/snapraid.content

# Excludes hidden files and directories
snapraid_exclude_hidden: false

# Defines files and directories to exclude
snapraid_excludes:
  - "*.unrecoverable"
  - /tmp/
  - /lost+found/

# Defines the block size in kibi bytes (1024 bytes)
# snapraid_blocksize: 256

# Defines the hash size in bytes.
# WARNING: Changing this value is for experts only!
# snapraid_hashsize: 16

# Automatically save the state when syncing after the specified amount
# of GB processed.
# This option is useful to avoid to restart from scratch long 'sync'
# commands interrupted by a machine crash.
# It also improves the recovering if a disk break during a 'sync'.
# snapraid_autosave: 0

# Defines the pooling directory where the virtual view of the disk
# array is created using the "pool" command.
# The files are not really copied here, but just linked using
# symbolic links.
# This directory must be outside the array.
# snapraid_pool: /pool
snapraid_pool_permissions: '0755'
