---
transmission_wg_enabled: false
transmission_wg_available_externally: false

# secrets
transmission_client_username: ""
transmission_client_password: ""

# directories
transmission_wg_config_directory: "{{ docker_home }}/transmission-wg/config"
transmission_config_directory: "{{ docker_home }}/transmission/config"
transmission_download_directory: "{{ downloads_root }}"
transmission_watch_directory: "{{ torrents_root }}"

# uid / gid
transmission_user_id: "1000"
transmission_group_id: "1000"
transmission_wg_user_id: "1000"
transmission_wg_group_id: "1000"

# network
transmission_webui_port: "9092"
transmission_external_port: "51414"
transmission_peer_port: "54914"
transmission_timezone: "{{ ansible_nas_timezone }}"
transmission_hostname: "transmission-wg"

# specs
transmission_memory: 1g