---
- name: Create Syncthing Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ syncthing_samba_data_directory }}"

- name: Syncthing Docker Container
  docker_container:
    name: "{{ syncthing_samba_hostname }}"
    image: syncthing/syncthing:latest
    pull: true
    ports:
      - "{{ syncthing_samba_port_http }}:8384"
      - "{{ syncthing_samba_port_sync }}:22000/tcp"
      - "{{ syncthing_samba_port_sync }}:22000/udp"
    env:
      PUID: "{{ syncthing_samba_user_id }}"
      PGID: "{{ syncthing_samba_group_id }}"
    volumes: "{{ syncthing_samba_volumes }}"
    restart_policy: unless-stopped
    memory : "{{ syncthing_samba_memory }}"
    labels:
      traefik.enable: "{{ syncthing_samba_available_externally | string }}"
      traefik.http.routers.syncthing-samba.rule: "Host(`{{ syncthing_samba_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.syncthing-samba.tls.certresolver: "letsencrypt"
      traefik.http.routers.syncthing-samba.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.syncthing-samba.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.syncthing-samba.loadbalancer.server.port: "8384"
